/*
 * This source file was generated by the Gradle 'init' task
 * TODO: Add in tests. That would be pretty darn cool.
 */
package net.mappingfixer.fmf;

import org.junit.jupiter.api.Test;

class TestMainSource {
    @Test void someLibraryMethodReturnsTrue() {
    	return;
    }
}
